PB-812 Naprawić nieprawidłowo wyświetlającą się cenę
upsellpl/WPI-Cart pull request #37
Opened 2023-11-23 08:17 UTC by mbwawpl

2023-11-23 08:28 UTC, upsellpl requested changes

2023-11-23 08:28 UTC, upsellpl commented on includes/download-functions.php
> +    if (!$sales_enabled_key_exists) {
jeśli nie znajduje tego klucza to zwraca true? czyli jesli nie znajduje to jest enabled? dziwnie się to czyta...

2023-11-23 11:06 UTC, mbwawpl commented on includes/download-functions.php
> +    if (!$sales_enabled_key_exists) {
Tak, ta logika jest skopiowana z is_variant_sales_enabled w wolverine/product/Repository.php

2023-11-23 12:36 UTC, upsellpl commented on includes/download-functions.php
> +    if (!$sales_enabled_key_exists) {
no tam jest babol... przydałoby sie to wyjaśnić tu (i tam) opisowo.... ze brak klucza = enabled, by było to jasne jakoś

2023-11-24 03:01 UTC, mbwawpl commented on includes/download-functions.php
> +    if (!$sales_enabled_key_exists) {
W jakim sensie babol? Że to powinno działać inaczej, czy że niejasne jest, dlaczego tak działa jak teraz? Bo gdy dawniej nie było aktywowania sprzedaży na poziomie wariantu tylko kursu, to musimy przy braku tego ustawienia taki default przyjmować, że jest aktywny.

2023-11-24 11:57 UTC, upsellpl commented on includes/download-functions.php
> +    if (!$sales_enabled_key_exists) {
Że jet nieczytelne / niejasne.

gdy dawniej nie było aktywowania sprzedaży na poziomie wariantu tylko kursu, to musimy przy braku tego ustawienia taki default przyjmować, że jest aktywny.

no i to jest spoko - a da sie kod napisać tak by to nieco zawierał? wyciągając to do metody priv czy coś? (ale nie dając komentarz :))

2023-11-27 11:30 UTC, upsellpl approved these changes

2023-11-27 12:28 UTC, merged